version: '3.8'

services:
  mongodb-db:
    image: mongo:latest
    container_name: mongodb-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-db
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=productdb

volumes:
  mongodb-data: